name: Nilaway lint

on:
  pull_request:

jobs:
  nilaway-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5.0.1
      - uses: actions/setup-go@v5.0.1
        with:
          go-version: 1.22.4
      - run: make nilaway-lint
